; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[esp8266]
platform = espressif8266
board = d1_mini_lite
framework = arduino
lib_deps = 
    gilmaimon/ArduinoWebsockets@0.5.4
    ESP8266WiFi
    bblanchon/ArduinoJson@7.4.3
    makuna/NeoPixelBus@2.8.4
upload_speed = 115200
monitor_speed = 115200
build_flags =

[env:native]
platform = native
lib_deps = bblanchon/ArduinoJson@7.4.3
lib_compat_mode = off
test_framework = unity
build_flags = -lcrypto

[env:controller_1]
extends = esp8266
build_flags =
  '-DESP_NAME="controller1"'
  ${esp8266.build_flags}

[env:controller_1_ota]
extends = esp8266
build_flags =
  '-DESP_NAME="controller1"'
  ${esp8266.build_flags}
upload_port = controller1

[env:controller_2]
extends = esp8266
build_flags =
  '-DESP_NAME="controller2"'
  ${esp8266.build_flags}

[env:controller_2_ota]
extends = esp8266
build_flags =
  '-DESP_NAME="controller2"'
  ${esp8266.build_flags}
upload_protocol = espota
upload_port = controller2

[env:controller_3]
extends = esp8266
build_flags =
  '-DESP_NAME="controller3"'
  ${esp8266.build_flags}

[env:controller_3_ota]
extends = esp8266
build_flags =
  '-DESP_NAME="controller3"'
  ${esp8266.build_flags}
upload_protocol = espota
upload_port = controller3

[env:controller_4]
extends = esp8266
build_flags =
  '-DESP_NAME="controller4"'
  ${esp8266.build_flags}

[env:controller_4_ota]
extends = esp8266
build_flags =
  '-DESP_NAME="controller4"'
  ${esp8266.build_flags}
upload_protocol = espota
upload_port = controller4

[env:controller_5]
extends = esp8266
build_flags =
  '-DESP_NAME="controller5"'
  ${esp8266.build_flags}

[env:controller_5_ota]
extends = esp8266
build_flags =
  '-DESP_NAME="controller5"'
  ${esp8266.build_flags}
upload_protocol = espota
upload_port = controller5

[env:controller_6]
extends = esp8266
build_flags =
  '-DESP_NAME="controller6"'
  ${esp8266.build_flags}

[env:controller_6_ota]
extends = esp8266
build_flags =
  '-DESP_NAME="controller6"'
  ${esp8266.build_flags}
upload_protocol = espota
upload_port = controller6

[env:controller_7]
extends = esp8266
build_flags =
  '-DESP_NAME="controller7"'
  ${esp8266.build_flags}

[env:controller_7_ota]
extends = esp8266
build_flags =
  '-DESP_NAME="controller7"'
  ${esp8266.build_flags}
upload_protocol = espota
upload_port = controller7
